## Numpy some basics of arrays

In [2]:
import numpy as np


#### Creating arrays from list


In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("1D array:", arr_1d)
print("2D array:\n", arr_2d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### Difference b/w python list and numpy arrays

In [4]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])
print("Python list:", py_list *2)
print("NumPy array:", np_array *2)

Python list: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy array: [ 2  4  6  8 10]


#### Creating array from scratch

In [6]:
zeros = np.zeros((3, 3))
print("Zeros array:\n", zeros)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
ones = np.ones((3, 3))
print("Ones array:\n", ones)

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
full = np.full((3, 3), 7)
print("Full array:\n", full)

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
random = np.random.random((3, 3))
print("Random array:\n", random)

Random array:
 [[0.28409036 0.78955576 0.72819449]
 [0.49443628 0.68408941 0.2323333 ]
 [0.44586945 0.95365242 0.25485497]]


In [11]:
sequence = np.arange(0, 10, 2)
print("Arange array:", sequence)

Arange array: [0 2 4 6 8]


### Vector , matrix and tensor

In [13]:
vector = np.array([3,4,5,6])
print("Vector:", vector)

matrix = np.array([[1,2,4] , [5,6,7]])
print("Matrix:\n", matrix)

tensor = np.array([[[1,2,3], [4,5,6]],
                    [[7,8,9], [10,11,12]]])
print("Tensor:\n", tensor)


Vector: [3 4 5 6]
Matrix:
 [[1 2 4]
 [5 6 7]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Array properties

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print("Array size:", arr.size)
print("Array dtype:", arr.dtype)
print("Array itemsize:", arr.itemsize)
print("Array nbytes:", arr.nbytes)
print("Array Dimension:", arr.ndim)

Array shape: (2, 3)
Array size: 6
Array dtype: int64
Array itemsize: 8
Array nbytes: 48
Array Dimension: 2


#### Array reshaping

In [18]:
arr = np.arange(12)
print("Original array:", arr)
reshaped = arr.reshape(3, 4)    
print("Reshaped array:\n", reshaped)
flattend = reshaped.flatten()
print("Flattened array:", flattend)

transposed = reshaped.T
print("Transposed array:\n", transposed)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
