## Numpy array operations

In [ ]:
import numpy as np


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("basic slicing" , arr[1:5])
print("With step" , arr[1:5:2])

basic slicing [2 3 4 5]
With step [2 4]


#### 2d arrray

In [12]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element" , arr_2d[1, 2])
print("Row slicing" , arr_2d[1])
print("Column slicing" , arr_2d[:,1])

Specific element 6
Row slicing [4 5 6]
Column slicing [2 5 8]


#### sorting

In [16]:
unsorted = np.array([3, 1, 2, 5, 4])
print("sorted array" ,np.sort( unsorted))

arr_2d = np.array([[3, 1, 2], [5, 4, 6], [7, 8, 9]])
print("sorted array" ,np.sort( arr_2d, axis=0)) # sort by column

sorted array [1 2 3 4 5]
sorted array [[3 1 2]
 [5 4 6]
 [7 8 9]]


### Filtering in arrays

In [17]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("even numbers" , even_numbers)

even numbers [ 2  4  6  8 10]


### Filter with mask

In [18]:
mask = numbers>5
print("Numbers greater than 5 are" , numbers[mask])


Numbers greater than 5 are [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [21]:
indices = [0,3,5]
print("Using indices" , numbers[indices])
where_result = np.where(numbers > 5)
print(where_result) # returns a tuple of arrays
print("Using where" , numbers[where_result])

Using indices [1 4 6]
(array([5, 6, 7, 8, 9]),)
Using where [ 6  7  8  9 10]


In [23]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print("Using where with condition" , condition_array)

Using where with condition [ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate((arr1, arr2))
print("concatenated array" , combined)

concatenated array [1 2 3 4 5 6]


#### Array compatibility

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("compatibility check" , a.shape == b.shape == c.shape)

compatibility check True


In [6]:
original_array = np.array([[1, 2], [3, 4], [5, 6]])
new_row = np.array([[7, 8]])
combined_array = np.vstack((original_array, new_row))
new_col = np.array([[9], [10], [11]])
combined_array2 = np.hstack((original_array, new_col))
print("original_array" , original_array)
print("Vertical stacking" , combined_array)
print("Horizontal stacking" , combined_array2)

original_array [[1 2]
 [3 4]
 [5 6]]
Vertical stacking [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacking [[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]]
