#### Data structure : [resturent_id, 2021, 2022, 2023, 2024]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
import numpy as np
sales_data = np.array([
    [1, 15000, 18000, 20000, 5000], #paradise biryani
    [2, 12000, 16000, 19000, 23000], #bejing bites
    [3, 17000, 20000, 22000, 26000], #pizza hub
    [4, 13000, 17000, 21000, 24000], #burger point
    [5, 14000, 19000, 23000, 27000], #chai point
])

print("=== Zomato sales data ===")
print("\n sales data shape", sales_data.shape)
print("\n Sales data for 1st three resturants" , sales_data[:3])

=== Zomato sales data ===

 sales data shape (5, 5)

 Sales data for 1st three resturants [[    1 15000 18000 20000  5000]
 [    2 12000 16000 19000 23000]
 [    3 17000 20000 22000 26000]]


### Total sales per year

In [ ]:
print(np.sum(sales_data, axis=0)) #sum of sales data for all resturants
yearly_total = print(np.sum(sales_data[:, 1:], axis=0)) #sum of sales data for all resturants

#minmum sales per resturent
print("\n Minimum sales per restaurant", np.min(sales_data[:, 1:], axis=1))

#maximum sales per resturent
print("\n Maximum sales per restaurant", np.max(sales_data[:, 1:], axis=0))

#average sales per resturent
print("\n Average sales per restaurant", np.mean(sales_data[:, 1:], axis=1))

[    15  71000  90000 105000 105000]
[ 71000  90000 105000 105000]

 Minimum sales per restaurant [ 5000 12000 17000 13000 14000]

 Maximum sales per restaurant [17000 20000 23000 27000]


In [5]:
import numpy as np;
vector1= np.array([1, 2, 3])
vector2= np.array([4, 5, 6])

print("\n Vector1 + Vector2 = ", vector1 + vector2) #element wise addition
print("\n Vector1 - Vector2 = ", vector1 - vector2) #element wise subtraction
print("\n Vector1 * Vector2 = ", vector1 * vector2) #element wise multiplication
print("\n Vector1 / Vector2 = ", vector1 / vector2) #element wise division
angle = np.arccos(np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2))) #angle between two vectors
print("\n Angle between vector1 and vector2 = ", angle) #angle between two vectors



 Vector1 + Vector2 =  [5 7 9]

 Vector1 - Vector2 =  [-3 -3 -3]

 Vector1 * Vector2 =  [ 4 10 18]

 Vector1 / Vector2 =  [0.25 0.4  0.5 ]

 Angle between vector1 and vector2 =  0.2257261285527342


In [6]:
ipl_teams = np.array(['kkr','csk','rcb','mi','dc','rr','gt','pbks'])
vectorized_teams = np.vectorize(str.upper)
print("\n Vectorized teams = ", vectorized_teams(ipl_teams)) #vectorized teams


 Vectorized teams =  ['KKR' 'CSK' 'RCB' 'MI' 'DC' 'RR' 'GT' 'PBKS']
