In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [6]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr
arr.shape

(4, 3)

In [7]:
arr.size

12

In [10]:
arr.min()

np.int64(1)

In [11]:
arr.max()

np.int64(12)

In [12]:
np.sum(arr,axis=0)

array([22, 26, 30])